### ISSUE TITLE
May I please fork your repository?

### ISSUE THREAD

**Issue by willowell** [Solonarv/adventofcode-2021#1]
Hi there!

Please excuse me for my out-of-the-blue question!

I'm from the Functional Programming Discord server. I followed your AOC 2020 repo because I was (and still am!) learning Haskell, and I really enjoyed your work and found it easy to understand.

May I please fork your repository, delete your solutions in my fork, and use it for my solutions?

Of course, I will keep and fully respect the GPL v3 license you added.

Thank you for reading my question!

**Comment by Solonarv** [comment]
The license already grants you the permission you need, you don't need to ask.
